apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot
  namespace: pavithra
  labels:
    app: dot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dot
  template:
    metadata:
      labels:
        app: dot
    spec:
      containers:
      - name: dot
        image: pavithra7194/dotnet:1.0 # Replace with your Docker image
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: pavi
