apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: pavithra
spec:
  selector:
    app: dotnet
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
