apiVersion: v1
kind: Service
metadata:
  name: dotnet
spec:
  selector:
    app: dotnet
    namespace: pavithra
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
