apiVersion: apps/v1
kind: Deployment
metadata:
  name: dot
  namespace: pavithrak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dot
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dot
    spec:
      containers:
        - name: dot
          image: nikitha2109/nikithaimage:1.0.1
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: special
          operator: Equal
          value: example
